### ISSUE TITLE
Need help with returning hash table using powershell

### ISSUE THREAD

**Issue by anotherPassword** [tgeorgiev/vro-polyglot-scripts#1]
Hi,
You give the example
    # Hashtable output, make sure the action return type is Properties of CompositeType
    # $output=@{status = 'done'}
return $output

I am trying to set vm tags using powershell, like I did in javascript. In javascript I just returned properties. 
(inputProperties is type properties, and tags is type properties)
var tags = inputProperties.tags || new Properties();
tags.put("JavaTag1","Tag1");
tags.put("JavaTag2","Tag2");

in powershell, with a scriptable task, how do I create the correct return values so it works same as javascript? I am not sure what a 'Properties of CompositeType' is. 
thanks,
ds

**Comment by tgeorgiev** [comment]
Hi,

so in the above example, I am creating a hash table with one entry with key "status" and value "done". To have the same as you wrote in JavaScript it will be

$tags = @{}
$tags.Add("PSTag1", "Tag1")
$tags.Add("PSTag2", "Tag2")

Also for  'Properties of CompositeType' there is a type, that should be  'Properties **OR** CompositeType'.

Hope this helps!

**Comment by anotherPassword** [comment]
Yeah, I tried exactly that with the output type 'Properties', it does not seem to work. Not sure how I would do this with a composite type.
